# Generated by Django 6.0.4 on 2026-05-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminoperatorprofile',
            options={'ordering': ['user__username'], 'permissions': [('access_admin_panel', 'Can access the admin operations panel')]},
        ),
    ]
