# Generated by Django 6.0.4 on 2026-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_adminoperatorprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoperatorprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('administrator', 'Administrator'), ('operator', 'Operator')], default='operator', max_length=20),
        ),
    ]
