# Generated by Django 6.0.4 on 2026-04-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0010_assign_default_location_to_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=220)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='draft', max_length=16)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.company')),
            ],
            options={
                'ordering': ['company', '-starts_on', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ContractOptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_extra_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_rules', to='contracts.contract')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_rules', to='booking.serviceoption')),
            ],
            options={
                'ordering': ['contract', 'option'],
            },
        ),
        migrations.CreateModel(
            name='ContractServiceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rules', to='contracts.contract')),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_rules', to='booking.serviceoffering')),
            ],
            options={
                'ordering': ['contract', 'service_offering'],
            },
        ),
        migrations.CreateModel(
            name='ContractVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='contracts.contract')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_vehicles', to='booking.vehicletype')),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_contract_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='contractoptionrule',
            constraint=models.UniqueConstraint(fields=('contract', 'option'), name='unique_option_rule_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='contractservicerule',
            constraint=models.UniqueConstraint(fields=('contract', 'service_offering'), name='unique_service_rule_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='contractvehicle',
            constraint=models.UniqueConstraint(fields=('contract', 'vehicle_number'), name='unique_vehicle_number_per_contract'),
        ),
    ]
