# Generated by Django 6.0.4 on 2026-05-02 21:19

from django.db import migrations, models


VEHICLE_NUMBER_TRANSLATION = str.maketrans(
    {
        "А": "A",
        "В": "B",
        "С": "C",
        "Е": "E",
        "Н": "H",
        "І": "I",
        "К": "K",
        "М": "M",
        "О": "O",
        "Р": "P",
        "Т": "T",
        "Х": "X",
        "Ё": "E",
        "Ї": "I",
        "Й": "Y",
        "З": "Z",
        "Л": "L",
        "У": "Y",
    }
)


def normalize_vehicle_number(value):
    if not isinstance(value, str):
        return ""

    translated = value.upper().translate(VEHICLE_NUMBER_TRANSLATION)
    return "".join(char for char in translated if char.isalnum())


def fill_normalized_vehicle_numbers(apps, schema_editor):
    ContractVehicle = apps.get_model("contracts", "ContractVehicle")

    for vehicle in ContractVehicle.objects.all():
        vehicle.normalized_vehicle_number = normalize_vehicle_number(vehicle.vehicle_number)
        vehicle.save(update_fields=["normalized_vehicle_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_normalized_vehicle_number'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractvehicle',
            options={'ordering': ['normalized_vehicle_number', 'vehicle_number']},
        ),
        migrations.RemoveConstraint(
            model_name='contractvehicle',
            name='unique_vehicle_number_per_contract',
        ),
        migrations.AddField(
            model_name='contractvehicle',
            name='normalized_vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.RunPython(fill_normalized_vehicle_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contractvehicle',
            constraint=models.UniqueConstraint(fields=('contract', 'normalized_vehicle_number'), name='unique_normalized_vehicle_number_per_contract'),
        ),
    ]
