# Generated by Django 6.0.4 on 2026-04-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default settings', max_length=120)),
                ('slot_step_minutes', models.PositiveIntegerField(default=15)),
                ('booking_days_ahead', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business settings',
                'verbose_name_plural': 'Business settings',
                'ordering': ['-is_active', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_default', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='operations.location')),
            ],
            options={
                'verbose_name': 'Business hours',
                'verbose_name_plural': 'Business hours',
                'ordering': ['location', 'weekday', 'opens_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('telegram_username', models.CharField(blank=True, max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_contacts', to='operations.location')),
            ],
            options={
                'ordering': ['-is_primary', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_breaks', to='operations.location')),
            ],
            options={
                'ordering': ['location', 'weekday', 'starts_at'],
            },
        ),
    ]
