# Generated by Django 6.0.4 on 2026-04-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_servicepost_location'),
        ('operations', '0002_seed_default_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbreak',
            name='service_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_breaks', to='booking.servicepost'),
        ),
        migrations.CreateModel(
            name='ServicePostHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('service_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='booking.servicepost')),
            ],
            options={
                'verbose_name': 'Service post hours',
                'verbose_name_plural': 'Service post hours',
                'ordering': ['service_post', 'weekday', 'opens_at'],
            },
        ),
    ]
