# Generated by Django 6.0.4 on 2026-05-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0011_booking_normalized_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('retail', 'Retail'), ('contract', 'Contract')], default='retail', max_length=16)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOfferingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='pricing.pricelist')),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='booking.serviceoffering')),
            ],
            options={
                'ordering': ['price_list', 'service_offering'],
                'constraints': [models.UniqueConstraint(fields=('price_list', 'service_offering'), name='unique_service_offering_price_per_price_list')],
            },
        ),
        migrations.CreateModel(
            name='ServiceOptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='booking.serviceoption')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_prices', to='pricing.pricelist')),
            ],
            options={
                'ordering': ['price_list', 'option'],
                'constraints': [models.UniqueConstraint(fields=('price_list', 'option'), name='unique_service_option_price_per_price_list')],
            },
        ),
    ]
