# Generated by Django 6.0.4 on 2026-04-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.SlugField(max_length=96, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('applicable_group', models.CharField(blank=True, max_length=32)),
                ('option_group', models.CharField(blank=True, max_length=64)),
                ('select_mode', models.CharField(choices=[('single', 'Single'), ('multi', 'Multi')], default='multi', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('passenger', 'Passenger'), ('cargo', 'Cargo'), ('tanker', 'Tanker'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='booking.service')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_offerings', to='booking.vehicletype')),
            ],
            options={
                'ordering': ['service__title', 'vehicle_type__group', 'vehicle_type__title'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('done', 'Done'), ('no_show', 'No show')], default='new', max_length=16)),
                ('client_type', models.CharField(choices=[('retail', 'Retail'), ('contract', 'Contract'), ('system', 'System')], default='retail', max_length=16)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('admin', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.client')),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.serviceoffering')),
                ('options', models.ManyToManyField(blank=True, related_name='bookings', to='booking.serviceoption')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='applicable_vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='available_options', to='booking.vehicletype'),
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.UniqueConstraint(fields=('service', 'vehicle_type'), name='unique_service_offering_per_vehicle_type'),
        ),
    ]
