# Generated by Django 6.0.4 on 2026-04-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoption',
            old_name='duration_minutes',
            new_name='extra_duration_minutes',
        ),
    ]
