# Generated by Django 6.0.4 on 2026-04-26 20:23

import django.db.models.deletion
from django.db import migrations, models


def seed_vehicle_groups(apps, schema_editor):
    VehicleGroup = apps.get_model("booking", "VehicleGroup")
    groups = [
        ("passenger", "Passenger"),
        ("cargo", "Cargo"),
        ("tanker", "Tanker"),
        ("other", "Other"),
    ]
    for group_id, title in groups:
        VehicleGroup.objects.get_or_create(id=group_id, defaults={"title": title})


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_duration_minutes_serviceoption_extra_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGroup',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RunPython(seed_vehicle_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='serviceoption',
            name='applicable_group',
            field=models.ForeignKey(blank=True, db_column='applicable_group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='available_options', to='booking.vehiclegroup'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='group',
            field=models.ForeignKey(db_column='group', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='booking.vehiclegroup'),
        ),
    ]
