# Generated by Django 6.0.4 on 2026-04-27 07:07

import django.db.models.deletion
from django.db import migrations, models


def seed_default_service_post(apps, schema_editor):
    ServicePost = apps.get_model("booking", "ServicePost")
    ServicePost.objects.get_or_create(
        id="post_1",
        defaults={
            "title": "Пост 1",
            "sort_order": 1,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_vehiclegroup_alter_serviceoption_applicable_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.servicepost'),
        ),
        migrations.RunPython(seed_default_service_post, migrations.RunPython.noop),
    ]
