# Generated by Django 6.0.4 on 2026-04-27 07:15

from django.db import migrations, models


def assign_all_options_to_existing_posts(apps, schema_editor):
    ServiceOption = apps.get_model("booking", "ServiceOption")
    ServicePost = apps.get_model("booking", "ServicePost")
    option_ids = list(ServiceOption.objects.filter(is_active=True).values_list("id", flat=True))
    for post in ServicePost.objects.all():
        post.supported_options.add(*option_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_assign_default_post_to_existing_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='supported_options',
            field=models.ManyToManyField(blank=True, related_name='service_posts', to='booking.serviceoption'),
        ),
        migrations.RunPython(assign_all_options_to_existing_posts, migrations.RunPython.noop),
    ]
