# Generated by Django 6.0.4 on 2026-04-27 07:24

import django.db.models.deletion
from django.db import migrations, models


def seed_supported_services_and_allocations(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    BookingPostAllocation = apps.get_model("booking", "BookingPostAllocation")
    Service = apps.get_model("booking", "Service")
    ServicePost = apps.get_model("booking", "ServicePost")

    service_ids = list(Service.objects.filter(is_active=True).values_list("id", flat=True))
    for post in ServicePost.objects.all():
        post.supported_services.add(*service_ids)

    for booking in Booking.objects.select_related("service_post", "service_offering__service"):
        if not booking.service_post_id:
            continue

        BookingPostAllocation.objects.get_or_create(
            booking=booking,
            sort_order=0,
            defaults={
                "service_post": booking.service_post,
                "service": booking.service_offering.service,
                "starts_at": booking.starts_at,
                "ends_at": booking.ends_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_servicepost_supported_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='supported_services',
            field=models.ManyToManyField(blank=True, related_name='service_posts', to='booking.service'),
        ),
        migrations.CreateModel(
            name='BookingPostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_allocations', to='booking.booking')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_allocations', to='booking.service')),
                ('service_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_allocations', to='booking.serviceoption')),
                ('service_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_allocations', to='booking.servicepost')),
            ],
            options={
                'ordering': ['starts_at', 'sort_order'],
                'indexes': [models.Index(fields=['service_post', 'starts_at', 'ends_at'], name='booking_boo_service_693897_idx')],
            },
        ),
        migrations.RunPython(seed_supported_services_and_allocations, migrations.RunPython.noop),
    ]
