# Generated by Django 6.0.4 on 2026-04-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_add_other_transport_type'),
        ('operations', '0002_seed_default_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_posts', to='operations.location'),
        ),
    ]
