# Generated by Django 6.0.4 on 2026-05-02 21:19

from django.db import migrations, models


VEHICLE_NUMBER_TRANSLATION = str.maketrans(
    {
        "А": "A",
        "В": "B",
        "С": "C",
        "Е": "E",
        "Н": "H",
        "І": "I",
        "К": "K",
        "М": "M",
        "О": "O",
        "Р": "P",
        "Т": "T",
        "Х": "X",
        "Ё": "E",
        "Ї": "I",
        "Й": "Y",
        "З": "Z",
        "Л": "L",
        "У": "Y",
    }
)


def normalize_vehicle_number(value):
    if not isinstance(value, str):
        return ""

    translated = value.upper().translate(VEHICLE_NUMBER_TRANSLATION)
    return "".join(char for char in translated if char.isalnum())


def fill_normalized_vehicle_numbers(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")

    for booking in Booking.objects.all():
        booking.normalized_vehicle_number = normalize_vehicle_number(booking.vehicle_number)
        booking.save(update_fields=["normalized_vehicle_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_assign_default_location_to_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='normalized_vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.RunPython(fill_normalized_vehicle_numbers, migrations.RunPython.noop),
    ]
