# Generated by Django 6.0.4 on 2026-05-09 21:35

import django.db.models.deletion
from django.db import migrations, models


def link_existing_options_to_compatible_offerings(apps, schema_editor):
    ServiceOffering = apps.get_model("booking", "ServiceOffering")
    ServiceOfferingOption = apps.get_model("booking", "ServiceOfferingOption")
    ServiceOption = apps.get_model("booking", "ServiceOption")

    options = list(ServiceOption.objects.filter(is_active=True).order_by("title", "id"))
    offerings = ServiceOffering.objects.select_related("vehicle_type").filter(
        is_active=True,
        service__is_active=True,
        vehicle_type__is_active=True,
        vehicle_type__group__is_active=True,
    )

    for offering in offerings:
        sort_order = 0
        for option in options:
            group_ok = (
                not option.applicable_group_id
                or option.applicable_group_id == offering.vehicle_type.group_id
            )
            vehicle_ok = (
                not option.applicable_vehicle_type_id
                or option.applicable_vehicle_type_id == offering.vehicle_type_id
            )
            if not group_ok or not vehicle_ok:
                continue

            ServiceOfferingOption.objects.get_or_create(
                service_offering=offering,
                option=option,
                defaults={
                    "is_active": True,
                    "is_required": False,
                    "sort_order": sort_order,
                },
            )
            sort_order += 10


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_deactivate_legacy_tanker_vehicle_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOfferingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_duration_override', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offering_links', to='booking.serviceoption')),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_options', to='booking.serviceoffering')),
            ],
            options={
                'ordering': ['sort_order', 'option__title'],
                'constraints': [models.UniqueConstraint(fields=('service_offering', 'option'), name='unique_option_per_service_offering')],
            },
        ),
        migrations.RunPython(
            link_existing_options_to_compatible_offerings,
            migrations.RunPython.noop,
        ),
    ]
